### ISSUE TITLE
Packet foward builder 

### ISSUE THREAD

**Issue by memocl** [mpous/helium-data-hotspot#4]
Build packet forwarder is giving error and closeing

Info]              Starting build for helium-data-hotspot, user g_guillermo_cavazos_lamelas
[Info]              Dashboard link: https://dashboard.balena-cloud.com/apps/1876165/devices
[Info]              Building on arm05
[Info]              Pulling previous images for caching purposes...
[Success]           Successfully pulled cache images
[Info]              Starting to build packet-forwarder
[Info]              Starting to build helium-miner
[Success]           Successfully built service helium-miner
[Info]              Uploading images
[Success]           Successfully uploaded images
[Error]             Some services failed to build:
[Error]               Service: packet-forwarder
[Error]                 Error: The command '/bin/sh -c ./buildfiles/compileSX1301.sh spidev0.0' returned a non-zero code: 1
[Info]              Built on arm05
[Error]             Not deploying release.

Total noob here, please be patient.

**Comment by memocl** [comment]
> @memocl where are you getting this error? on `balena push`?

Identical case as @chronos000 . His english and computing knowledge is better than mine. So seems than not only me is getting the error.

**Comment by johnfrancisli** [comment]
Also getting this error. Looking for advice.

**Comment by memocl** [comment]
> @memocl where are you getting this error? on `balena push`?

Yes, still getting the error on balena push

**Comment by ngiester** [comment]
@mpous much like @memocl I'm experiencing the same issue on the packet-forwarder docker container image builder. Appreciate anyone's assistance. 

[Info]              Starting build for helium-data-hotspot, user (Blanked out)
[Info]              Dashboard link: https://dashboard.balena-cloud.com/apps/(Blanked out)devices
[Info]              Building on arm03
[Info]              Pulling previous images for caching purposes...
[Success]           Successfully pulled cache images
[Info]              Starting to build packet-forwarder
[Info]              Starting to build helium-miner
[Success]           Successfully built service helium-miner
[Info]              Uploading images
[Success]           Successfully uploaded images
**[Error]             Some services failed to build:
[Error]               Service: packet-forwarder
[Error]                 Error: The command '/bin/sh -c ./buildfiles/compileSX1301.sh spidev0.0' returned a non-zero code: 1
[Info]              Built on arm03
[Error]             Not deploying release.**

Packet -forwarder Docker container logs

Step 1/37 : FROM balenalib/raspberry-pi-debian:buster-build as builder
 ---> 683d83ad6e81
Step 2/37 : WORKDIR /opt/iotloragateway/dev
 ---> Running in 8a043450cca3
Removing intermediate container 8a043450cca3
 ---> 25c0d1702d54
Step 3/37 : COPY requirements.txt requirements.txt
 ---> f4ddab9199b9
Step 4/37 : ENV PATH="/opt/iotloragateway/dev/venv/bin:$PATH"
 ---> Running in f54239a8163c
Removing intermediate container f54239a8163c
 ---> ddd9179edfe9
Step 5/37 : RUN apt-get update &&     apt-get -y install --no-install-recommends         automake         libtool         autoconf         git         ca-certificates         pkg-config         build-essential         python3         python3-pip         python3-venv
 ---> Running in 10ef93926dd2
Here are a few details about this Docker image (For more information please visit https://www.balena.io/docs/reference/base-images/base-images/): 
Architecture: ARM v6 
OS: Debian Buster 
Variant: build variant 
Default variable(s): UDEV=off 
Extra features: 
- Easy way to install packages with `install_packages <package-name>` command 
- Run anywhere with cross-build feature  (for ARM only) 
- Keep the container idling with `balena-idle` command 
- Show base image details with `balena-info` command
Get:1 http://archive.raspbian.org/raspbian buster InRelease [15.0 kB]
Get:2 http://archive.raspberrypi.org/debian buster InRelease [32.6 kB]
Get:3 http://archive.raspbian.org/raspbian buster/firmware armhf Packages [1201 B]
Get:4 http://archive.raspbian.org/raspbian buster/main armhf Packages [18.3 MB]
Get:5 http://archive.raspberrypi.org/debian buster/main armhf Packages [393 kB]
Get:6 http://archive.raspbian.org/raspbian buster/rpi armhf Packages [1299 B]
Get:7 http://archive.raspbian.org/raspbian buster/non-free armhf Packages [126 kB]
Get:8 http://archive.raspbian.org/raspbian buster/contrib armhf Packages [68.6 kB]
Fetched 18.9 MB in 3s (5848 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
autoconf is already the newest version (2.69-11).
automake is already the newest version (1:1.16.1-4).
automake set to manually installed.
build-essential is already the newest version (12.6).
ca-certificates is already the newest version (20200601~deb10u2).
git is already the newest version (1:2.20.1-2+deb10u3).
pkg-config is already the newest version (0.29-6).
pkg-config set to manually installed.
python3 is already the newest version (3.7.3-1).
python3 set to manually installed.
The following package was automatically installed and is no longer required:
  libidn11
Use 'apt autoremove' to remove it.
The following additional packages will be installed:
  file libmagic-mgc libmagic1 python-pip-whl python3.7-venv
Suggested packages:
  libtool-doc gfortran | fortran95-compiler gcj-jdk
Recommended packages:
  python3-dev python3-setuptools python3-wheel
The following NEW packages will be installed:
  file libmagic-mgc libmagic1 libtool python-pip-whl python3-pip python3-venv
  python3.7-venv
0 upgraded, 8 newly installed, 0 to remove and 12 not upgraded.
Need to get 2733 kB of archives.
After this operation, 9738 kB of additional disk space will be used.
Get:1 http://archive.raspberrypi.org/debian buster/main armhf python-pip-whl all 18.1-5+rpt1 [1591 kB]
Get:2 http://archive.raspbian.org/raspbian buster/main armhf libmagic-mgc armhf 1:5.35-4+deb10u2 [242 kB]
Get:3 http://archive.raspberrypi.org/debian buster/main armhf python3-pip all 18.1-5+rpt1 [171 kB]
Get:4 http://archive.raspbian.org/raspbian buster/main armhf libmagic1 armhf 1:5.35-4+deb10u2 [110 kB]
Get:5 http://archive.raspbian.org/raspbian buster/main armhf file armhf 1:5.35-4+deb10u2 [65.5 kB]
Get:6 http://archive.raspbian.org/raspbian buster/main armhf libtool all 2.4.6-9 [547 kB]
Get:7 http://archive.raspbian.org/raspbian buster/main armhf python3.7-venv armhf 3.7.3-2+deb10u3 [6148 B]
Get:8 http://archive.raspbian.org/raspbian buster/main armhf python3-venv armhf 3.7.3-1 [1180 B]
debconf: delaying package configuration, since apt-utils is not installed

Fetched 2733 kB in 1s (3195 kB/s)
Selecting previously unselected package libmagic-mgc.
(Reading database ... 
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
24611 files and directories currently installed.)
Preparing to unpack .../0-libmagic-mgc_1%3a5.35-4+deb10u2_armhf.deb ...
Unpacking libmagic-mgc (1:5.35-4+deb10u2) ...
Selecting previously unselected package libmagic1:armhf.
Preparing to unpack .../1-libmagic1_1%3a5.35-4+deb10u2_armhf.deb ...
Unpacking libmagic1:armhf (1:5.35-4+deb10u2) ...
Selecting previously unselected package file.
Preparing to unpack .../2-file_1%3a5.35-4+deb10u2_armhf.deb ...
Unpacking file (1:5.35-4+deb10u2) ...
Selecting previously unselected package libtool.
Preparing to unpack .../3-libtool_2.4.6-9_all.deb ...
Unpacking libtool (2.4.6-9) ...
Selecting previously unselected package python-pip-whl.
Preparing to unpack .../4-python-pip-whl_18.1-5+rpt1_all.deb ...
Unpacking python-pip-whl (18.1-5+rpt1) ...
Selecting previously unselected package python3-pip.
Preparing to unpack .../5-python3-pip_18.1-5+rpt1_all.deb ...
Unpacking python3-pip (18.1-5+rpt1) ...
Selecting previously unselected package python3.7-venv.
Preparing to unpack .../6-python3.7-venv_3.7.3-2+deb10u3_armhf.deb ...
Unpacking python3.7-venv (3.7.3-2+deb10u3) ...
Selecting previously unselected package python3-venv.
Preparing to unpack .../7-python3-venv_3.7.3-1_armhf.deb ...
Unpacking python3-venv (3.7.3-1) ...
Setting up libmagic-mgc (1:5.35-4+deb10u2) ...
Setting up libmagic1:armhf (1:5.35-4+deb10u2) ...
Setting up file (1:5.35-4+deb10u2) ...
Setting up python-pip-whl (18.1-5+rpt1) ...
Setting up libtool (2.4.6-9) ...
Setting up python3.7-venv (3.7.3-2+deb10u3) ...
Setting up python3-venv (3.7.3-1) ...
Setting up python3-pip (18.1-5+rpt1) ...
Processing triggers for libc-bin (2.28-10+rpi1) ...
Removing intermediate container 10ef93926dd2
 ---> 911d213d9bfb
Step 6/37 : RUN python3 -m venv /opt/iotloragateway/dev/venv &&     pip install --no-cache-dir -r requirements.txt
 ---> Running in ab0b529e42aa
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting sentry-sdk==1.1.0 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/1c/4a/a54b254f67d8f4052338d54ebe90126f200693440a93ef76d254d581e3ec/sentry_sdk-1.1.0-py2.py3-none-any.whl (131kB)
Collecting hm-hardware-defs==0.1.6a3 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/1c/ba/df76e12831bf793fcedf7766cd1d18553cf62d40ca2407bea59f030a1ad3/hm_hardware_defs-0.1.6a3-py3-none-any.whl
Collecting certifi (from sentry-sdk==1.1.0->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/37/45/946c02767aabb873146011e665728b680884cd8fe70dde973c640e45b775/certifi-2021.10.8-py2.py3-none-any.whl (149kB)
Collecting urllib3>=1.10.0 (from sentry-sdk==1.1.0->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/af/f4/524415c0744552cce7d8bf3669af78e8a069514405ea4fcbd0cc44733744/urllib3-1.26.7-py2.py3-none-any.whl (138kB)
Installing collected packages: certifi, urllib3, sentry-sdk, hm-hardware-defs
Successfully installed certifi-2021.10.8 hm-hardware-defs-0.1.6a3 sentry-sdk-1.1.0 urllib3-1.26.7
Removing intermediate container ab0b529e42aa
 ---> f01fa31abbae
Step 7/37 : COPY buildfiles buildfiles
 ---> 3e005338b93f
Step 8/37 : COPY sx1302fixes sx1302fixes
 ---> bd463601a4b7
Step 9/37 : RUN git clone https://github.com/NebraLtd/lora_gateway.git
 ---> Running in 00ad4a3fcb6f
Cloning into 'lora_gateway'...

Removing intermediate container 00ad4a3fcb6f
 ---> 39243686a6de
Step 10/37 : RUN git clone https://github.com/NebraLtd/packet_forwarder.git
 ---> Running in 19c9b1836af9
Cloning into 'packet_forwarder'...

Removing intermediate container 19c9b1836af9
 ---> 20550f139984
Step 11/37 : RUN mkdir -p /opt/iotloragateway/packetforwarder
 ---> Running in 14ab40692de7
Removing intermediate container 14ab40692de7
 ---> a04318a2c5d4
Step 12/37 : RUN ./buildfiles/compileSX1301.sh spidev0.0
 ---> Running in e4a5ffd9ec1b
Compiling for spidev0.0
cp: cannot stat 'src/loragw_spi.native.c.template': No such file or directory

sed: can't read src/loragw_spi.native.c: No such file or directory

rm -f libloragw.a
rm -f test_loragw_*
rm -f obj/*.o
rm -f inc/config.h
mkdir -p obj
*** Checking libloragw library configuration ***
make: *** No rule to make target 'src/loragw_spi.native.c', needed by 'obj/loragw_spi.o'.  Stop.
make: *** Waiting for unfinished jobs....

#File initialization
# Release version
Release version   : 5.0.1
# Debug options
# end of file
*** Configuration seems ok ***
make clean -e -C lora_pkt_fwd
make[1]: Entering directory '/opt/iotloragateway/dev/packet_forwarder/lora_pkt_fwd'
rm -f obj/*.o
rm -f lora_pkt_fwd
make[1]: Leaving directory '/opt/iotloragateway/dev/packet_forwarder/lora_pkt_fwd'
make clean -e -C util_ack
make[1]: Entering directory '/opt/iotloragateway/dev/packet_forwarder/util_ack'
rm -f obj/*.o
rm -f util_ack
make[1]: Leaving directory '/opt/iotloragateway/dev/packet_forwarder/util_ack'
make clean -e -C util_sink
make[1]: Entering directory '/opt/iotloragateway/dev/packet_forwarder/util_sink'
rm -f obj/*.o
rm -f util_sink
make[1]: Leaving directory '/opt/iotloragateway/dev/packet_forwarder/util_sink'
make clean -e -C util_tx_test
make[1]: Entering directory '/opt/iotloragateway/dev/packet_forwarder/util_tx_test'
rm -f obj/*.o
rm -f util_tx_test
make[1]: Leaving directory '/opt/iotloragateway/dev/packet_forwarder/util_tx_test'
make all -e -C lora_pkt_fwd
make[1]: Entering directory '/opt/iotloragateway/dev/packet_forwarder/lora_pkt_fwd'
mkdir -p obj
make[1]: *** No rule to make target '../../lora_gateway/libloragw/libloragw.a', needed by 'lora_pkt_fwd'.  Stop.
make[1]: *** Waiting for unfinished jobs....

make[1]: Leaving directory '/opt/iotloragateway/dev/packet_forwarder/lora_pkt_fwd'
make: *** [Makefile:11: all] Error 2

cp: cannot stat '/opt/iotloragateway/dev/packet_forwarder/lora_pkt_fwd/lora_pkt_fwd': No such file or directory

Removing intermediate container e4a5ffd9ec1b
The command '/bin/sh -c ./buildfiles/compileSX1301.sh spidev0.0' returned a non-zero code: 1

**Comment by adventis312** [comment]
[packet-forwarder]  The command '/bin/sh -c ./buildfiles/compileSX1301.sh spidev0.0' returned a non-zero code: 126
[Info]              Uploading images
[Success]           Successfully uploaded images
[Error]             Some services failed to build:
[Error]               Service: packet-forwarder
[Error]                 Error: The command '/bin/sh -c ./buildfiles/compileSX1301.sh spidev0.0' returned a non-zero code: 126
[Info]              Built on arm04
[Error]             Not deploying release.
Remote build failed

**Comment by mpous** [comment]
@chronos000 @johnfrancisli @adventis312 @ngiester with the new PR submitted this should build now. Test and let me know if that works for you! Thanks

**Comment by johnfrancisli** [comment]
Still receiving the same error.
